from enum import Enum

class CheckType(Enum):
    MISSING_TAGS = 'MISSING_TAGS'
    NO_MFA_ON_ROOT = 'NO_MFA_ON_ROOT'
    NO_PASSWORD_POLICY = 'NO_PASSWORD_POLICY'
    PUBLIC_BUCKETS = 'PUBLIC_BUCKETS'
    NO_BUSINESS_SUPPORT = 'NO_BUSINESS_SUPPORT'
    NO_BUDGET = 'NO_BUDGET'